Vagrant.configure("2") do |config|

  # İlk makine: k3smaster
  config.vm.define "k3smaster" do |k3smaster|
    k3smaster.vm.box = "ubuntu/focal64"
    k3smaster.vm.box_download_insecure = true

    # Sabit IP ile Public Network
    k3smaster.vm.network "public_network", ip: "192.168.1.48", bridge: "Realtek PCIe GbE Family Controller", auto_config: true

    # Port çakışmalarını önlemek için auto_correct
    k3smaster.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true

    k3smaster.vm.provider "virtualbox" do |vb|
      vb.memory = "4000"
      vb.cpus = 2
    end

    k3smaster.vm.provision "shell", path: "mastersh.sh", privileged: true
  end

  # İkinci makine: k3sworker
  config.vm.define "k3sworker" do |k3sworker|
    k3sworker.vm.box = "ubuntu/focal64"
    k3sworker.vm.box_download_insecure = true

    # Sabit IP ile Public Network
    k3sworker.vm.network "public_network", ip: "192.168.1.49", bridge: "Realtek PCIe GbE Family Controller", auto_config: true

    # Port çakışmalarını önlemek için auto_correct
    k3sworker.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh", auto_correct: true

    k3sworker.vm.provider "virtualbox" do |vb|
      vb.memory = "3000"
      vb.cpus = 2
    end

    k3sworker.vm.provision "shell", path: "workersh.sh", privileged: true
  end


end
