Vagrant.configure("2") do |config|

  # Ubuntu: robotdreams
  config.vm.define "robotdreams" do |robotdreams|
    robotdreams.vm.box = "ubuntu/focal64"
	config.vm.box_download_insecure=true
	config.vm.boot_timeout
    robotdreams.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
	robotdreams.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	 vb.cpus = 2
   end
    robotdreams.vm.provision "shell", path: "setup-robotdreams.sh", privileged: true
  end


end
